/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

/**
 * Exports the Zowe MCP Server capabilities as a JSON file in MCP Server Card format,
 * aligned with SEP-1649 (.well-known/mcp/server-card.json).
 *
 * The output contains static listings of tools, prompts, resources, and resource
 * templates. Zowe-specific metadata (capabilityTier) is placed in the _meta extension
 * namespace using the MCP registry convention.
 *
 * Usage:
 *   npx @zowe/mcp-server server-card [--output <path>] [--capability-tier <tier>]
 *
 * Default output: docs/mcp-server-card.json (relative to cwd)
 * Default tier:   full (exports all tools)
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type CapabilityTier, TIER_NAMES } from '../capability-level.js';
import { Logger } from '../log.js';
import { buildServerCard } from '../server-card.js';

const log = new Logger({ name: 'server-card' });

interface ParsedCliArgs {
  output: string;
  capabilityTier: CapabilityTier;
}

function parseArgs(): ParsedCliArgs {
  const args = process.argv.slice(2);
  let output: string | undefined;
  let capabilityTier: string | undefined;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--output' && i + 1 < args.length) {
      output = args[++i];
    } else if (args[i].startsWith('--output=')) {
      output = args[i].slice(9);
    } else if (args[i] === '--capability-tier' && i + 1 < args.length) {
      capabilityTier = args[++i];
    } else if (args[i].startsWith('--capability-tier=')) {
      capabilityTier = args[i].slice(18);
    }
  }
  if (
    capabilityTier !== undefined &&
    !(TIER_NAMES as readonly string[]).includes(capabilityTier)
  ) {
    process.stderr.write(
      `Invalid --capability-tier "${capabilityTier}". Valid values: ${TIER_NAMES.join(', ')}\n`
    );
    process.exit(1);
  }
  return {
    output: output ?? resolve(process.cwd(), 'docs', 'mcp-server-card.json'),
    capabilityTier: (capabilityTier as CapabilityTier | undefined) ?? 'full',
  };
}

async function main(): Promise<void> {
  const { output, capabilityTier } = parseArgs();
  log.info('Generating MCP server card', { output, capabilityTier });

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const indexJsPath = resolve(__dirname, '..', 'index.js');

  const card = await buildServerCard(indexJsPath, capabilityTier);
  card._generated =
    'This file is auto-generated by `npx @zowe/mcp-server server-card`. ' +
    'Do not edit manually — run `npx @zowe/mcp-server server-card` to regenerate.';

  log.info('Collected MCP capabilities', {
    tools: card.tools.length,
    prompts: card.prompts.length,
    resources: card.resources.length,
    resourceTemplates: card.resourceTemplates.length,
  });

  const outputDir = dirname(output);
  mkdirSync(outputDir, { recursive: true });
  writeFileSync(output, JSON.stringify(card, null, 2) + '\n', 'utf-8');
  log.info(`Schema written to ${output}`);
  process.stdout.write(`Schema written to ${output}\n`);
}

main().catch((error: unknown) => {
  log.error('Error', error);
  process.exit(1);
});
