/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

/**
 * Exports the Zowe MCP Server capabilities as a JSON file in MCP Server Card format,
 * aligned with SEP-2127 (draft) (`GET /mcp/server-card`).
 *
 * SEP-2127 deliberately excludes tool/prompt/resource listings from the Server Card
 * itself — they remain subject to runtime listing via the protocol's list methods —
 * so this CLI's static listings of tools, prompts, and resource templates are placed
 * in the `_meta` extension namespace alongside Zowe-specific metadata (capabilityTier),
 * using the MCP registry convention. This vendor extension exists only in this file's
 * output, never in the card served over HTTP.
 *
 * Usage:
 *   npx @zowe/mcp-server server-card [--output <path>] [--capability-tier <tier>]
 *
 * Default output: docs/mcp-server-card.json (relative to cwd)
 * Default tier:   full (exports all tools)
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type CapabilityTier, TIER_NAMES } from '../capability-level.js';
import { Logger } from '../log.js';
import { buildServerCard, SERVER_CARD_NAME } from '../server-card.js';

const log = new Logger({ name: 'server-card' });

interface ParsedCliArgs {
  output: string;
  capabilityTier: CapabilityTier;
}

function parseArgs(): ParsedCliArgs {
  const args = process.argv.slice(2);
  let output: string | undefined;
  let capabilityTier: string | undefined;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--output' && i + 1 < args.length) {
      output = args[++i];
    } else if (args[i].startsWith('--output=')) {
      output = args[i].slice(9);
    } else if (args[i] === '--capability-tier' && i + 1 < args.length) {
      capabilityTier = args[++i];
    } else if (args[i].startsWith('--capability-tier=')) {
      capabilityTier = args[i].slice(18);
    }
  }
  if (
    capabilityTier !== undefined &&
    !(TIER_NAMES as readonly string[]).includes(capabilityTier)
  ) {
    process.stderr.write(
      `Invalid --capability-tier "${capabilityTier}". Valid values: ${TIER_NAMES.join(', ')}\n`
    );
    process.exit(1);
  }
  return {
    output: output ?? resolve(process.cwd(), 'docs', 'mcp-server-card.json'),
    capabilityTier: (capabilityTier as CapabilityTier | undefined) ?? 'full',
  };
}

async function main(): Promise<void> {
  const { output, capabilityTier } = parseArgs();
  log.info('Generating MCP server card', { output, capabilityTier });

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const indexJsPath = resolve(__dirname, '..', 'index.js');

  const card = await buildServerCard(
    indexJsPath,
    capabilityTier,
    'This file is auto-generated by `npx @zowe/mcp-server server-card`. ' +
      'Do not edit manually — run `npx @zowe/mcp-server server-card` to regenerate.'
  );

  const docsExtras = card._meta?.[SERVER_CARD_NAME] as
    | { tools?: unknown[]; prompts?: unknown[]; resourceTemplates?: unknown[] }
    | undefined;
  log.info('Collected MCP capabilities', {
    tools: docsExtras?.tools?.length ?? 0,
    prompts: docsExtras?.prompts?.length ?? 0,
    resourceTemplates: docsExtras?.resourceTemplates?.length ?? 0,
  });

  const outputDir = dirname(output);
  mkdirSync(outputDir, { recursive: true });
  writeFileSync(output, JSON.stringify(card, null, 2) + '\n', 'utf-8');
  log.info(`Schema written to ${output}`);
  process.stdout.write(`Schema written to ${output}\n`);
}

main().catch((error: unknown) => {
  log.error('Error', error);
  process.exit(1);
});
