/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

/**
 * Type definitions for the CLI plugin bridge.
 *
 * The bridge reads YAML metadata files that describe how Zowe CLI plugin commands
 * map to MCP tools. The execution engine spawns `zowe <command> --rfj` subprocesses,
 * using named connection profiles whose credentials are resolved via the same
 * password store as the native z/OS backend.
 *
 * All plugin-specific details (profile type definitions, field names, CLI option
 * names) are defined in the plugin YAML — no plugin-specific code belongs here.
 */

// ---------------------------------------------------------------------------
// Description variants (shared by all description-bearing nodes)
// ---------------------------------------------------------------------------

/**
 * Description variants for a tool — allows A/B testing of description quality.
 *
 * Any variant name is valid (the index signature accepts any key).  The active
 * variant is resolved by `resolveDescription()` using this priority:
 *   tool.activeDescription > plugin.activeDescription > ZOWE_MCP_CLI_DESC_VARIANT > 'intent' > 'cli' > first available
 *
 * **JSON-path reference syntax**: any variant value (including profile field `description`)
 * that starts with `$.` is treated as a dotted path into a companion
 * `<plugin>-commands.json` file located next to the plugin YAML.
 * The loader resolves the reference at load time and replaces the `$.path`
 * string with the value found in the JSON.
 *
 * Example:
 * ```yaml
 * descriptions:
 *   cli: "$.endevor.list.environments.description"
 *   intent: "Lists all available Endevor environments..."
 * ```
 */
export interface DescriptionVariants {
  /** Original wording from the CLI --help text (or a `$.path` JSON reference). */
  cli?: string;
  /** Intent-centric rewrite designed for AI agents. */
  intent?: string;
  /** LLM-optimized, generated by rephrase-tool-descriptions script. */
  optimized?: string;
  [key: string]: string | undefined;
}

// ---------------------------------------------------------------------------
// Profile type definitions (YAML-driven)
// ---------------------------------------------------------------------------

/**
 * A single field in a named profile type (e.g. host, user, environment).
 *
 * Supports the same `description`/`descriptions` dual pattern as every other
 * description-bearing node; `$.path` references are resolved against the
 * companion `<plugin>-commands.json` at load time.
 */
export interface ProfileFieldDef {
  /** Field name used as the key in named profile instances (camelCase). */
  name: string;
  /** CLI option name without '--' (e.g. 'host', 'env', 'sn'). */
  cliOption?: string;
  /**
   * Plain description string (fallback for all variants).
   * May be a `$.dotted.path` JSON reference resolved against the companion JSON.
   */
  description?: string;
  /** Per-variant description strings. */
  descriptions?: DescriptionVariants;
  /** When true, this field must be present in every profile of this type. */
  required?: boolean;
  /** Default value injected when the field is absent from the profile and the tool call. */
  default?: string;
  /**
   * When true, this field's value is the username for password lookup.
   * The password is keyed as `user@host` (where `host` is the field named "host").
   */
  isUsername?: boolean;
}

/**
 * Defines one named-profile type in the `profiles:` YAML block.
 *
 * Two flags control the runtime behaviour for every tool that uses this type:
 *   - `required`         — a profile of this type must be active (or passed per-tool)
 *   - `perToolOverride`  — individual fields are injected into each tool's input schema
 *
 * Tool descriptions are auto-generated from `name` when no explicit
 * `listDescription`/`setDescription` (or their `*Descriptions` variant siblings) are given.
 */
export interface ProfileTypeDef {
  /** Human-readable label, e.g. "Endevor connection". Used in auto-generated descriptions. */
  name: string;
  /** MCP tool name for listing profiles of this type (e.g. endevorListConnections). */
  toolListName: string;
  /** MCP tool name for setting the active profile (e.g. endevorSetConnection). */
  toolSetName: string;
  /**
   * When true a profile of this type MUST be active (or passed as `<typeKey>Id`)
   * before any tool can be invoked.  Auto-selects when exactly one profile is loaded.
   */
  required: boolean;
  /**
   * When true, individual fields of this type are injected into each tool's input
   * schema (controlled per-tool by `locationParams`).  A `<typeKey>Id` per-tool
   * parameter is also added to let the caller prime from a named profile per call.
   *
   * When false, only a `<typeKey>Id` override parameter is added to tools;
   * individual fields are NOT exposed in the tool schemas.
   */
  perToolOverride: boolean;
  /** Plain description for the list tool. Auto-generated from `name` when absent. */
  listDescription?: string;
  /** Variant descriptions for the list tool. */
  listDescriptions?: DescriptionVariants;
  /** Plain description for the set tool. Auto-generated from `name` when absent. */
  setDescription?: string;
  /** Variant descriptions for the set tool. */
  setDescriptions?: DescriptionVariants;
  /** Profile fields (non-sensitive; password is managed via the password store). */
  fields: ProfileFieldDef[];
}

// ---------------------------------------------------------------------------
// Runtime named profiles
// ---------------------------------------------------------------------------

/**
 * A single named profile instance loaded from the config file.
 * The `id` field is required; all other keys are profile field values.
 */
export interface CliNamedProfile {
  id: string;
  [field: string]: string | number | boolean | undefined;
}

/**
 * Config file format for CLI plugin named profiles.
 *
 * The top-level keys match the profile type keys defined in the plugin YAML's
 * `profiles:` block (e.g. "connection", "location"). This shape is generic so
 * any plugin's profile types are supported without code changes.
 *
 * Example (Endevor):
 * ```json
 * {
 *   "connection": {
 *     "profiles": [{ "id": "prod", "host": "zos.prod.com", "user": "U1", "instance": "ENDEVOR" }],
 *     "default": "prod"
 *   },
 *   "location": {
 *     "profiles": [{ "id": "dev", "environment": "DEV", "stageNumber": "1" }]
 *   }
 * }
 * ```
 */
export type CliPluginProfilesFile = Record<
  string,
  { profiles: CliNamedProfile[]; default?: string }
>;

// ---------------------------------------------------------------------------
// Password resolver
// ---------------------------------------------------------------------------

/**
 * Resolves the password for a given user@host pair.
 * Implementations may read from env vars (standalone) or from the shared
 * WaitablePasswordStore (VS Code mode).
 */
export interface CliPluginPasswordResolver {
  getPassword(user: string, host: string): Promise<string>;
}

// ---------------------------------------------------------------------------
// YAML-driven tool definition
// ---------------------------------------------------------------------------

/** A single extra parameter for a tool. */
export interface PluginParam {
  /** MCP parameter name (camelCase). */
  name: string;
  /**
   * CLI option name without '--' (e.g. env, sn, sys, search, data).
   * When set, the value is passed as `--<cliOption> <value>`.
   */
  cliOption?: string;
  /**
   * When true, this parameter is passed as a positional argument
   * (the first bare word after the sub-command), not as --option value.
   */
  cliPositional?: boolean;
  /**
   * Plain description string (fallback for all variants).
   * May be a `$.dotted.path` JSON reference resolved against the companion
   * `<plugin>-commands.json` file. Optional when `descriptions` is provided.
   */
  description?: string;
  /**
   * Per-variant description strings (same resolution order as tool descriptions:
   * active variant → intent → cli → description plain).
   */
  descriptions?: DescriptionVariants;
  /** Whether this parameter is required. */
  required?: boolean;
  /** Default value if not provided by the caller. */
  default?: string;
}

/** A single MCP tool definition in the plugin YAML. */
export interface PluginToolDef {
  /** MCP tool name (camelCase with plugin prefix, e.g. endevorListElements). */
  toolName: string;
  /**
   * The `zowe` command string to execute, e.g. "endevor list elements".
   * The bridge prepends "zowe" and appends "--rfj" plus connection profile args.
   */
  zoweCommand: string;
  /**
   * Which description variant to use for this tool.
   * Falls back to the plugin-level activeDescription, then env ZOWE_MCP_CLI_DESC_VARIANT,
   * then 'intent', then first available.
   */
  activeDescription?: string;
  /** Description text variants. */
  descriptions: DescriptionVariants;
  /** When true, VS Code skips the confirmation dialog before calling this tool. */
  readOnlyHint?: boolean;
  /** When true, VS Code shows a warning before calling this tool. */
  destructiveHint?: boolean;
  /**
   * When true, automatically inject all `perToolOverride: true` profile fields
   * as optional parameters (with virtual context defaults).
   * When a string array, only the named fields are injected.
   */
  locationParams?: boolean | string[];
  /** Additional tool-specific parameters beyond the location params. */
  params?: PluginParam[];
  /**
   * Key to extract from the parsed --rfj JSON response.
   * Default: "data". Use "stdout" for text output (e.g. print element content).
   * Use "." for the entire response body.
   */
  outputPath?: string;
}

// ---------------------------------------------------------------------------
// Top-level plugin YAML config
// ---------------------------------------------------------------------------

/** Top-level structure of a plugin YAML metadata file. */
export interface CliPluginConfig {
  /** Plugin identifier, e.g. "endevor". */
  plugin: string;
  /**
   * Human-readable display name shown in error messages and logs,
   * e.g. "Endevor". Falls back to `plugin` when absent.
   */
  displayName?: string;
  /**
   * Default active description variant for all tools that don't specify their own.
   * Can be overridden at runtime by ZOWE_MCP_CLI_DESC_VARIANT env var.
   */
  activeDescription?: string;
  /**
   * Named profile type definitions. Keys are arbitrary type identifiers
   * (e.g. "connection", "location"); values describe the type's fields and behaviour.
   */
  profiles?: Record<string, ProfileTypeDef>;
  /** Tool definitions. */
  tools: PluginToolDef[];
}

// ---------------------------------------------------------------------------
// Runtime session state
// ---------------------------------------------------------------------------

/** Mutable container for the plugin session state. */
export interface CliPluginState {
  /** Loaded named profiles per type key (e.g. "connection", "location"). */
  profilesByType: Map<string, CliNamedProfile[]>;
  /**
   * Currently active profile ID per type key.
   * For `required: true` types the active ID is set at startup (auto-select or default)
   * or by calling the set tool.
   */
  activeProfileId: Map<string, string | undefined>;
  /**
   * Virtual field context per type key for `perToolOverride: true` types.
   * Updated by the set tool (e.g. endevorSetLocation): primed from a named profile,
   * then individual field overrides applied on top.  Used as defaults for tool calls.
   */
  virtualContextByType: Map<string, Record<string, string | undefined>>;
  /**
   * Resolves password for user@host.  Only needed when at least one profile type
   * has `required: true` and contains a field with `isUsername: true`.
   */
  passwordResolver?: CliPluginPasswordResolver;
  /**
   * Called whenever activeProfileId or virtualContextByType changes.
   * Set by the server to forward the updated active profiles to the VS Code extension.
   */
  onActiveProfilesChanged?: () => void;
  /**
   * Where this plugin's configuration came from.
   * Used to tailor remediation hints in error messages:
   * - 'vscode' — configuration arrived via the VS Code extension pipe (zoweMCP.cliPluginConfiguration)
   * - 'cli'    — configuration came from a file passed via --cli-plugin-connection / mcp.json
   */
  configSource?: 'vscode' | 'cli';
  /**
   * When set (VS Code mode only), sends a notification to the VS Code extension so the user
   * sees a native error dialog in addition to the in-chat error message.
   *
   * @param message     - Human-readable description of the problem.
   * @param severity    - 'info' | 'warning' | 'error'
   * @param settingsKey - When provided, the notification shows only an "Open Settings" button
   *                      that opens this specific settings key (no "Generate Mock Data" button).
   */
  sendNotification?: (
    message: string,
    severity: 'info' | 'warning' | 'error',
    settingsKey?: string
  ) => void;
}
