/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

/**
 * Type definitions for the CLI plugin bridge.
 *
 * The bridge reads YAML metadata files that describe how Zowe CLI plugin commands
 * map to MCP tools. The execution engine spawns `zowe <command> --rfj` subprocesses,
 * using named connection profiles whose credentials are resolved via the same
 * password store as the native z/OS backend.
 *
 * All plugin-specific details (profile type definitions, field names, CLI option
 * names) are defined in the plugin YAML — no plugin-specific code belongs here.
 */

// ---------------------------------------------------------------------------
// Description variants (shared by all description-bearing nodes)
// ---------------------------------------------------------------------------

/**
 * Description variants for a tool — allows A/B testing of description quality.
 *
 * Any variant name is valid (the index signature accepts any key).  The active
 * variant is resolved by `resolveDescription()` using this priority:
 *   tool.activeDescription > plugin.activeDescription > ZOWE_MCP_CLI_DESC_VARIANT > 'optimized' > 'cli' > first available
 *
 * **JSON-path reference syntax**: any variant value (including profile field `description`)
 * that starts with `$.` is treated as a dotted path into a companion
 * `<plugin>-commands.yaml` (or `.json`) file located next to the plugin YAML.
 * The loader resolves the reference at load time and replaces the `$.path`
 * string with the value found in the file.
 *
 * Example:
 * ```yaml
 * descriptions:
 *   cli: "$.endevor.list.environments.description"
 *   optimized: "Lists all available Endevor environments..."
 * ```
 */
export interface DescriptionVariants {
  /** Original wording from the CLI --help text (or a `$.path` JSON reference). */
  cli?: string;
  /** LLM-optimized, generated by rephrase-tool-descriptions script. */
  optimized?: string;
  [key: string]: string | undefined;
}

// ---------------------------------------------------------------------------
// Profile type definitions (YAML-driven)
// ---------------------------------------------------------------------------

/**
 * A single field in a named profile type (e.g. host, user, environment).
 *
 * Supports the same `description`/`descriptions` dual pattern as every other
 * description-bearing node; `$.path` references are resolved against the
 * companion `<plugin>-commands.json` at load time.
 */
export interface ProfileFieldDef {
  /** Field name used as the key in named profile instances (camelCase). */
  name: string;
  /** CLI option name without '--' (e.g. 'host', 'env', 'sn'). */
  cliOption?: string;
  /**
   * Plain description string (fallback for all variants).
   * May be a `$.dotted.path` JSON reference resolved against the companion JSON.
   */
  description?: string;
  /** Per-variant description strings. */
  descriptions?: DescriptionVariants;
  /** When true, this field must be present in every profile of this type. */
  required?: boolean;
  /** Default value injected when the field is absent from the profile and the tool call. */
  default?: string;
  /**
   * When true, this field's value is the username for password lookup.
   * The password is keyed as `user@host` (where `host` is the field named "host").
   */
  isUsername?: boolean;
}

/**
 * Defines one named-profile type in the `profiles:` YAML block.
 *
 * Two flags control the runtime behaviour for every tool that uses this type:
 *   - `required`         — a profile of this type must be active (or passed per-tool)
 *   - `perToolOverride`  — individual fields are injected into each tool's input schema
 *
 * Tool descriptions are auto-generated from `name` when no explicit
 * `listDescription`/`setDescription` (or their `*Descriptions` variant siblings) are given.
 */
export interface ProfileTypeDef {
  /** Human-readable label, e.g. "Endevor connection". Used in auto-generated descriptions. */
  name: string;
  /** MCP tool name for listing profiles of this type (e.g. endevorListConnections). */
  toolListName: string;
  /** MCP tool name for setting the active profile (e.g. endevorSetConnection). */
  toolSetName: string;
  /**
   * When true a profile of this type MUST be active (or passed as `<typeKey>Id`)
   * before any tool can be invoked.  Auto-selects when exactly one profile is loaded.
   */
  required: boolean;
  /**
   * When true, individual fields of this type are injected into each tool's input
   * schema (controlled per-tool by `locationParams`).  A `<typeKey>Id` per-tool
   * parameter is also added to let the caller prime from a named profile per call.
   *
   * When false, only a `<typeKey>Id` override parameter is added to tools;
   * individual fields are NOT exposed in the tool schemas.
   */
  perToolOverride: boolean;
  /** Plain description for the list tool. Auto-generated from `name` when absent. */
  listDescription?: string;
  /** Variant descriptions for the list tool. */
  listDescriptions?: DescriptionVariants;
  /** Plain description for the set tool. Auto-generated from `name` when absent. */
  setDescription?: string;
  /** Variant descriptions for the set tool. */
  setDescriptions?: DescriptionVariants;
  /**
   * When set, registers an MCP tool that adds a named profile of this type, validates
   * fields, and persists (VS Code `zoweMCP.cliPluginConfiguration` and/or the
   * `--cli-plugin-configuration` file). Omit when profile lists are static.
   */
  toolAddProfileName?: string;
  /**
   * When set, registers an MCP tool that removes a named profile by id and persists.
   * If the removed profile was active, the first remaining profile becomes active (if any).
   */
  toolRemoveProfileName?: string;
  /** Profile fields (non-sensitive; password is managed via the password store). */
  fields: ProfileFieldDef[];
}

// ---------------------------------------------------------------------------
// Runtime named profiles
// ---------------------------------------------------------------------------

/**
 * A single named profile instance loaded from the config file.
 * The `id` field is required; all other keys are profile field values.
 */
export interface CliNamedProfile {
  id: string;
  [field: string]: string | number | boolean | undefined;
}

/**
 * Config file format for CLI plugin named profiles.
 *
 * The top-level keys match the profile type keys defined in the plugin YAML's
 * `profiles:` block (e.g. "connection", "location"). This shape is generic so
 * any plugin's profile types are supported without code changes.
 *
 * Example (Endevor):
 * ```json
 * {
 *   "connection": {
 *     "profiles": [{ "id": "prod", "host": "zos.prod.com", "user": "U1", "instance": "ENDEVOR" }],
 *     "default": "prod"
 *   },
 *   "location": {
 *     "profiles": [{ "id": "dev", "environment": "DEV", "stageNumber": "1" }]
 *   }
 * }
 * ```
 */
export type CliPluginProfilesFile = Record<
  string,
  { profiles: CliNamedProfile[]; default?: string }
>;

// ---------------------------------------------------------------------------
// Password resolver
// ---------------------------------------------------------------------------

/**
 * Resolves the password for a given user@host pair.
 * Implementations may read from env vars (standalone) or from the shared
 * WaitablePasswordStore (VS Code mode).
 */
export interface CliPluginPasswordResolver {
  getPassword(user: string, host: string): Promise<string>;
}

// ---------------------------------------------------------------------------
// Pagination and line windowing configuration
// ---------------------------------------------------------------------------

/**
 * Plugin-level defaults for list pagination tools.
 *
 * Values set here are inherited by every tool that opts in (explicitly or via
 * auto-detection). Per-tool `pagination:` overrides only the fields it specifies.
 */
export interface PluginListPaginationConfig {
  /** Default page size returned when the caller omits `limit` (default: 200). */
  defaultLimit?: number;
  /**
   * Hard upper bound on `limit` values from callers (default: 1000).
   * Values above this are clamped.
   */
  maxLimit?: number;
  /**
   * When set and the full CLI result exceeds this count, the tool uses MCP
   * elicitation (when the client supports it) or returns an informational
   * error asking the user to narrow the query.
   */
  maxResults?: number;
  /**
   * How long (in seconds) to keep cached CLI results (default: 300).
   */
  cacheTtlSeconds?: number;
  /**
   * Glob pattern(s) matched against tool names to automatically apply list
   * pagination without a per-tool `pagination:` block.
   *
   * Supports `*` as a wildcard (e.g. `"*List*"` matches `endevorListElements`).
   * Matching is case-insensitive.
   *
   * Examples:
   *   applyToPattern: "*List*"
   *   applyToPattern: ["*List*", "*Search*"]
   */
  applyToPattern?: string | string[];
}

/**
 * Plugin-level defaults for content windowing tools.
 *
 * Values set here are inherited by every tool that opts in (explicitly or via
 * auto-detection). Per-tool `pagination:` overrides only the fields it specifies.
 */
export interface PluginContentPaginationConfig {
  /** Default lines per window when the caller omits `lineCount` (default: 1000). */
  defaultLineCount?: number;
  /**
   * How long (in seconds) to keep cached CLI results (default: 300).
   */
  cacheTtlSeconds?: number;
  /**
   * When true (the default), content pagination is automatically applied to
   * every tool whose `outputPath` is `"stdout"`.
   * Set to `false` to require explicit per-tool `pagination: content`.
   */
  applyToStdout?: boolean;
  /**
   * Additional glob pattern(s) matched against tool names to automatically
   * apply content pagination (in addition to the `applyToStdout` rule).
   *
   * Supports `*` as a wildcard. Matching is case-insensitive.
   */
  applyToPattern?: string | string[];
}

/**
 * Plugin-level pagination configuration block.
 *
 * Placed at the root of a plugin YAML (next to `plugin:`, `profiles:`, `tools:`).
 * Provides default values and auto-application rules for all tools in the plugin.
 *
 * Example:
 * ```yaml
 * pagination:
 *   list:
 *     defaultLimit: 200
 *     maxLimit: 1000
 *     maxResults: 5000
 *     applyToPattern: "*List*"
 *   content:
 *     defaultLineCount: 1000
 *     # applyToStdout: true (default)
 * ```
 */
export interface PluginPaginationConfig {
  list?: PluginListPaginationConfig;
  content?: PluginContentPaginationConfig;
}

/**
 * Resolved per-tool pagination definition — the final effective config after
 * merging plugin defaults and per-tool overrides.
 *
 * Created by `resolveToolPagination()` in `cli-tool-loader.ts`; stored on the
 * resolved tool rather than the raw `PluginToolDef`.
 */
export interface PaginationDef {
  /**
   * Pagination mode:
   *   - 'list'    — adds `offset`/`limit` input params; wraps output array in
   *                 `ToolResponseEnvelope` with `ListResultMeta`.
   *   - 'content' — adds `startLine`/`lineCount` input params; wraps text
   *                 output in `ToolResponseEnvelope` with `ReadResultMeta`.
   */
  type: 'list' | 'content';

  // ---- 'list' options -------------------------------------------------------

  /** Default page size returned when the caller omits `limit` (default: 200). */
  defaultLimit?: number;

  /**
   * Hard upper bound on `limit` values from callers (default: 1000).
   * Values above this are clamped.
   */
  maxLimit?: number;

  /**
   * When set and the full CLI result exceeds this count, the tool uses MCP
   * elicitation (when the client supports it) or returns an informational
   * error to ask the user to narrow their query before fetching everything.
   *
   * The elicitation / error response uses `isError: false` so the LLM can
   * retry with more specific filter parameters.
   */
  maxResults?: number;

  // ---- 'content' options ----------------------------------------------------

  /**
   * Default number of lines returned per window when the caller omits
   * `lineCount` (default: 1000).
   */
  defaultLineCount?: number;

  // ---- Cache options --------------------------------------------------------

  /**
   * How long (in seconds) to keep cached CLI results before re-invoking.
   * Default: 300 (5 minutes).
   */
  cacheTtlSeconds?: number;
}

/**
 * Per-tool pagination override declaration.
 *
 * In the plugin YAML a tool can use any of these forms on the `pagination:` key:
 *
 * - `pagination: list`    — inherit plugin `pagination.list` defaults (type: list)
 * - `pagination: content` — inherit plugin `pagination.content` defaults (type: content)
 * - `pagination: false`   — explicitly opt out (suppress auto-detection)
 * - `pagination: { type: list, maxResults: 10000 }` — full or partial override;
 *                            unset fields are filled from plugin defaults
 * - omit `pagination:`    — auto-detect from plugin patterns and `outputPath`
 */
export type ToolPaginationSpec = PaginationDef | 'list' | 'content' | false;

// ---------------------------------------------------------------------------
// YAML-driven tool definition
// ---------------------------------------------------------------------------

/** A single extra parameter for a tool. */
export interface PluginParam {
  /** MCP parameter name (camelCase). */
  name: string;
  /**
   * CLI option name without '--' (e.g. env, sn, sys, search, data).
   * When set, the value is passed as `--<cliOption> <value>`.
   */
  cliOption?: string;
  /**
   * When true, this parameter is passed as a positional argument
   * (the first bare word after the sub-command), not as --option value.
   */
  cliPositional?: boolean;
  /**
   * Plain description string (fallback for all variants).
   * May be a `$.dotted.path` JSON reference resolved against the companion
   * `<plugin>-commands.json` file. Optional when `descriptions` is provided.
   */
  description?: string;
  /**
   * Per-variant description strings (same resolution order as tool descriptions:
   * active variant → optimized → cli → description plain).
   */
  descriptions?: DescriptionVariants;
  /** Whether this parameter is required. */
  required?: boolean;
  /** Default value if not provided by the caller. */
  default?: string;
  /**
   * Optional mapping from friendly MCP parameter values to CLI argument values.
   *
   * When present, `buildParamSchema` generates a `z.enum` of the map keys (friendly
   * names) wrapped in a `z.preprocess` normalizer that also accepts the raw CLI codes
   * (case-insensitive).  `buildCliArgs` translates the normalized friendly name back
   * to the CLI value before constructing the `--option value` pair.
   *
   * Accepts both friendly names and raw CLI codes (case-insensitive).
   * Invalid values are rejected by Zod with a message listing all valid friendly names.
   *
   * Example: `valueMap: { source: ES, history: EH, changes: EC }`
   * → `'source'`, `'SOURCE'`, `'ES'`, `'es'` all accepted; `'INVALID'` rejected
   * → CLI always receives `--search-in ES` (normalized from any accepted form)
   */
  valueMap?: Record<string, string>;
}

/** A single MCP tool definition in the plugin YAML. */
export interface PluginToolDef {
  /** MCP tool name (camelCase with plugin prefix, e.g. endevorListElements). */
  toolName: string;
  /**
   * The `zowe` command string to execute, e.g. "endevor list elements".
   * The bridge prepends "zowe" and appends "--rfj" plus connection profile args.
   */
  zoweCommand: string;
  /**
   * Which description variant to use for this tool.
   * Falls back to the plugin-level activeDescription, then env ZOWE_MCP_CLI_DESC_VARIANT,
   * then 'optimized', then 'cli', then first available.
   */
  activeDescription?: string;
  /** Description text variants. */
  descriptions: DescriptionVariants;
  /**
   * Resource effect level for capability-tier gating (required).
   *
   * Accepts a name (`none`, `read`, `update`, `delete`, `execute`)
   * or a number (0–4). MCP hints are derived automatically from this
   * value and the active capability tier.
   */
  resourceEffectLevel?: number | string;
  /** @deprecated Use `resourceEffectLevel` instead. Ignored when `resourceEffectLevel` is set. */
  readOnlyHint?: boolean;
  /** @deprecated Use `resourceEffectLevel` instead. Ignored when `resourceEffectLevel` is set. */
  destructiveHint?: boolean;
  /**
   * When true, automatically inject all `perToolOverride: true` profile fields
   * as optional parameters (with virtual context defaults).
   * When a string array, only the named fields are injected.
   */
  locationParams?: boolean | string[];
  /** Additional tool-specific parameters beyond the location params. */
  params?: PluginParam[];
  /**
   * Key to extract from the parsed --rfj JSON response.
   * Default: "data". Use "stdout" for text output (e.g. print element content).
   * Use "." for the entire response body.
   */
  outputPath?: string;
  /**
   * Pagination / line-windowing configuration for this tool.
   *
   * Shorthand values:
   *   - `'list'`    — inherit plugin-level `pagination.list` defaults
   *   - `'content'` — inherit plugin-level `pagination.content` defaults
   *   - `false`     — explicitly opt out of auto-detection
   *
   * Object form: full or partial `PaginationDef`; missing fields filled from
   * the matching plugin-level defaults (`pagination.list` or `pagination.content`).
   *
   * When omitted, auto-detection fires:
   *   - Tools with `outputPath: stdout` → content (when plugin.pagination.content is defined)
   *   - Tools matching `plugin.pagination.list.applyToPattern` → list
   *   - Tools matching `plugin.pagination.content.applyToPattern` → content
   */
  pagination?: ToolPaginationSpec;
  /**
   * When `false`, CLI invocation failures are returned as ordinary tool execution
   * errors (`isError: true`) rather than as fatal configuration errors (`stop: true`).
   *
   * Use for tools where the LLM may send invalid input that causes an error (e.g.
   * `db2ExecuteSql` where a bad SQL statement should be retryable, not fatal).
   * Defaults to `true` (current behaviour — all CLI errors are treated as
   * configuration errors that stop the LLM).
   */
  fatalOnCliError?: boolean;
}

// ---------------------------------------------------------------------------
// Top-level plugin YAML config
// ---------------------------------------------------------------------------

/** Top-level structure of a plugin YAML metadata file. */
export interface CliPluginConfig {
  /** Plugin identifier, e.g. "endevor". */
  plugin: string;
  /**
   * Human-readable display name shown in error messages and logs,
   * e.g. "Endevor". Falls back to `plugin` when absent.
   */
  displayName?: string;
  /**
   * Default active description variant for all tools that don't specify their own.
   * Can be overridden at runtime by ZOWE_MCP_CLI_DESC_VARIANT env var.
   */
  activeDescription?: string;
  /**
   * Plugin-level pagination defaults and auto-application rules.
   *
   * When set, tools can inherit these values with a simple `pagination: list` or
   * `pagination: content` shorthand, or be auto-detected based on `outputPath`
   * and name patterns — without repeating numeric limits on every tool.
   */
  pagination?: PluginPaginationConfig;
  /**
   * Named profile type definitions. Keys are arbitrary type identifiers
   * (e.g. "connection", "location"); values describe the type's fields and behaviour.
   */
  profiles?: Record<string, ProfileTypeDef>;
  /**
   * JavaScript regex patterns matched against CLI error messages that always
   * produce a fatal configuration error (`stop: true`), overriding
   * `retryableErrorPatterns` and `fatalOnCliError`.
   *
   * Use for known connection / network / driver-level errors that the LLM
   * cannot recover from (e.g. `"SQL30081N"` for Db2 network failure).
   */
  connectionErrorPatterns?: string[];
  /**
   * JavaScript regex patterns matched against CLI error messages that produce
   * a retryable tool execution error (`isError: true`, no `stop`).  Only
   * applied when no `connectionErrorPatterns` entry matches.
   *
   * Use when an error message reliably indicates that the CLI reached the
   * back-end service and the LLM can correct the input and retry
   * (e.g. `"\\[IBM\\]\\[CLI Driver\\]\\[DB2\\]"` for Db2 SQL execution errors).
   */
  retryableErrorPatterns?: string[];
  /**
   * Default error treatment when neither `connectionErrorPatterns` nor
   * `retryableErrorPatterns` match, and no per-tool `fatalOnCliError` is set.
   *
   * `true` (default) — unrecognised errors are fatal (`stop: true`).
   * `false` — unrecognised errors are retryable.
   *
   * Keeping the default as `true` preserves backward compatibility for plugins
   * that do not declare any patterns.
   */
  defaultCliErrorFatal?: boolean;
  /** Tool definitions. */
  tools: PluginToolDef[];
}

// ---------------------------------------------------------------------------
// Runtime session state
// ---------------------------------------------------------------------------

/** Mutable container for the plugin session state. */
export interface CliPluginState {
  /** Loaded named profiles per type key (e.g. "connection", "location"). */
  profilesByType: Map<string, CliNamedProfile[]>;
  /**
   * Currently active profile ID per type key.
   * For `required: true` types the active ID is set at startup (auto-select or default)
   * or by calling the set tool.
   */
  activeProfileId: Map<string, string | undefined>;
  /**
   * Virtual field context per type key for `perToolOverride: true` types.
   * Updated by the set tool (e.g. endevorSetLocation): primed from a named profile,
   * then individual field overrides applied on top.  Used as defaults for tool calls.
   */
  virtualContextByType: Map<string, Record<string, string | undefined>>;
  /**
   * Resolves password for user@host.  Only needed when at least one profile type
   * has `required: true` and contains a field with `isUsername: true`.
   */
  passwordResolver?: CliPluginPasswordResolver;
  /**
   * Called whenever activeProfileId or virtualContextByType changes.
   * Set by the server to forward the updated active profiles to the VS Code extension.
   */
  onActiveProfilesChanged?: () => void;
  /**
   * Where this plugin's configuration came from.
   * Used to tailor remediation hints in error messages:
   * - 'vscode' — configuration arrived via the VS Code extension pipe (zoweMCP.cliPluginConfiguration)
   * - 'cli'    — configuration came from a file passed via --cli-plugin-configuration / mcp.json
   */
  configSource?: 'vscode' | 'cli';
  /**
   * When set (VS Code mode only), sends a notification to the VS Code extension so the user
   * sees a native error dialog in addition to the in-chat error message.
   *
   * @param message     - Human-readable description of the problem.
   * @param severity    - 'info' | 'warning' | 'error'
   * @param settingsKey - When provided, the notification shows only an "Open Settings" button
   *                      that opens this specific settings key (no "Generate Mock Data" button).
   */
  sendNotification?: (
    message: string,
    severity: 'info' | 'warning' | 'error',
    settingsKey?: string
  ) => void;
  /**
   * Lazily initialised cache shared across all paginated/windowed tools for
   * this plugin instance.  Created on first use by `registerPluginTool()`.
   */
  _cliResultCache?: import('../../zos/response-cache.js').ResponseCache;
  /**
   * Persists the current {@link profilesByType} / {@link activeProfileId} to
   * `zoweMCP.cliPluginConfiguration` (when the VS Code extension is connected) and/or
   * the file passed with `--cli-plugin-configuration`. Set by the server entry point.
   */
  persistProfiles?: () => Promise<void>;
  /** Value of YAML `plugin:` — used as the key for VS Code `cliPluginConfiguration`. */
  pluginKey?: string;
  /** Absolute path from the CLI `--cli-plugin-configuration` file for this plugin. */
  persistConnectionFilePath?: string;
}
